from typing import Any, Optional, Union, Type, ClassVar
from collections.abc import Callable, Coroutine

from PyQt6.QtWidgets import QDoubleSpinBox


class FloatSpinBox(QDoubleSpinBox, BaseCustomWidget):
    def __init__(self: Any, value: Any) -> None: ...
    def setValue(self: Any, val: Any) -> None: ...
    def set_value(self: Any, value: Any) -> None: ...
    def value(self: Any) -> str: ...