# Script is not finished!
from typing import Any, Optional, Union, Type, ClassVar
from collections.abc import Callable, Coroutine

from PyQt6.QtWidgets import QWidget, QDialog


class PluginWidget(QWidget):
    def __init__(self: Any, name: Any, icon_path: Any, description: Any) -> None: ...
    def toggle_expansion(self: Any) -> None: ...
    def mousePressEvent(self: Any, event: Any) -> None: ...
class SettingsWindow(QDialog):
    def __init__(self: Any, plugins_data: Any) -> None: ...
    def init_ui(self: Any) -> None: ...
    def create_plugins_page(self: Any) -> None: ...
    def create_general_page(self: Any) -> None: ...
    def create_code_editor_page(self: Any) -> None: ...
    def create_appearance_page(self: Any) -> None: ...
    def change_page(self: Any, index: Any) -> None: ...