from typing import Any, Optional, Union, Type, ClassVar
from collections.abc import Callable, Coroutine

from UI.Elements.BaseCustomWidget import BaseCustomWidget


class SoundSelectWidget(BaseCustomWidget):
    def __init__(self: Any, value: Any) -> None: ...
    def valueChanged(self: Any, val: Any) -> None: ...
    def set_value(self: Any, value: str) -> None: ...
    def value(self: Any) -> None: ...