LIST_TYPES = {}
LIST_MOD_TEMPLATES = {}
LIST_PLANETS_TYPES = {}

ITEMS = {
    "Items.scrap":        {"displayName": "Scrap"},
    "Items.copper":       {"displayName": "Copper"},
    "Items.lead":         {"displayName": "Lead"},
    "Items.graphite":     {"displayName": "Graphite"},
    "Items.coal":         {"displayName": "Coal"},
    "Items.titanium":     {"displayName": "Titanium"},
    "Items.thorium":      {"displayName": "Thorium"},
    "Items.silicon":      {"displayName": "Silicon"},
    "Items.plastanium":   {"displayName": "Plastanium"},
    "Items.phaseFabric":  {"displayName": "Phase Fabric"},
    "Items.surgeAlloy":   {"displayName": "Surge Alloy"},
    "Items.sporePod":     {"displayName": "Spore Pod"},
    "Items.sand":         {"displayName": "Sand"},
    "Items.blastCompound":{"displayName": "Blast Compound"},
    "Items.pyratite":     {"displayName": "Pyratite"},
    "Items.metaglass":    {"displayName": "Metaglass"},
    "Items.beryllium":    {"displayName": "Beryllium"},
    "Items.tungsten":     {"displayName": "Tungsten"},
    "Items.oxide":        {"displayName": "Oxide"},
    "Items.carbide":      {"displayName": "Carbide"},
    "Items.fissileMatter":{"displayName": "Fissile Matter"},
    "Items.dormantCyst":  {"displayName": "Dormant Cyst"}
}

SOUND_TYPES_NOLOAD = {
    "Sound.artillery": {"displayName": "Artillery"},
    "Sound.back": {"displayName": "Back"},
    "Sound.bang": {"displayName": "Bang"},
    "Sound.beam": {"displayName": "Beam"},
    "Sound.bigshot": {"displayName": "Bigshot"},
    "Sound.bioLoop": {"displayName": "Bio Loop"},
    "Sound.blaster": {"displayName": "Blaster"},
    "Sound.bolt": {"displayName": "Bolt"},
    "Sound.boom": {"displayName": "Boom"},
    "Sound.breaks": {"displayName": "Breaks"},
    "Sound.build": {"displayName": "Build"},
    "Sound.buttonClick": {"displayName": "Button Click"},
    "Sound.cannon": {"displayName": "Cannon"},
    "Sound.chatMessage": {"displayName": "Chat Message"},
    "Sound.click": {"displayName": "Click"},
    "Sound.combustion": {"displayName": "Combustion"},
    "Sound.conveyor": {"displayName": "Conveyor"},
    "Sound.corexplode": {"displayName": "Corexplode"},
    "Sound.cutter": {"displayName": "Cutter"},
    "Sound.door": {"displayName": "Door"},
    "Sound.drill": {"displayName": "Drill"},
    "Sound.drillCharge": {"displayName": "Drill Charge"},
    "Sound.drillImpact": {"displayName": "Drill Impact"},
    "Sound.dullExplosion": {"displayName": "Dull Explosion"},
    "Sound.electricHum": {"displayName": "Electric Hum"},
    "Sound.explosion": {"displayName": "Explosion"},
    "Sound.explosionbig": {"displayName": "Explosionbig"},
    "Sound.extractLoop": {"displayName": "Extract Loop"},
    "Sound.fire": {"displayName": "Fire"},
    "Sound.flame": {"displayName": "Flame"},
    "Sound.flame2": {"displayName": "Flame 2"},
    "Sound.flux": {"displayName": "Flux"},
    "Sound.glow": {"displayName": "Glow"},
    "Sound.grinding": {"displayName": "Grinding"},
    "Sound.hum": {"displayName": "Hum"},
    "Sound.largeCannon": {"displayName": "Large Cannon"},
    "Sound.largeExplosion": {"displayName": "Large Explosion"},
    "Sound.laser": {"displayName": "Laser"},
    "Sound.laserbeam": {"displayName": "Laserbeam"},
    "Sound.laserbig": {"displayName": "Laserbig"},
    "Sound.laserblast": {"displayName": "Laserblast"},
    "Sound.lasercharge": {"displayName": "Lasercharge"},
    "Sound.lasercharge2": {"displayName": "Lasercharge 2"},
    "Sound.lasershoot": {"displayName": "Lasershoot"},
    "Sound.machine": {"displayName": "Machine"},
    "Sound.malignShoot": {"displayName": "Malign Shoot"},
    "Sound.mediumCannon": {"displayName": "Medium Cannon"},
    "Sound.message": {"displayName": "Message"},
    "Sound.mineDeploy": {"displayName": "Mine Deploy"},
    "Sound.minebeam": {"displayName": "Minebeam"},
    "Sound.missile": {"displayName": "Missile"},
    "Sound.missileLarge": {"displayName": "Missile Large"},
    "Sound.missileLaunch": {"displayName": "Missile Launch"},
    "Sound.missileSmall": {"displayName": "Missile Small"},
    "Sound.missileTrail": {"displayName": "Missile Trail"},
    "Sound.mud": {"displayName": "Mud"},
    "Sound.noammo": {"displayName": "Noammo"},
    "Sound.pew": {"displayName": "Pew"},
    "Sound.place": {"displayName": "Place"},
    "Sound.plantBreak": {"displayName": "Plant Break"},
    "Sound.plasmaboom": {"displayName": "Plasmaboom"},
    "Sound.plasmadrop": {"displayName": "Plasmadrop"},
    "Sound.press": {"displayName": "Press"},
    "Sound.pulse": {"displayName": "Pulse"},
    "Sound.pulseBlast": {"displayName": "Pulse Blast"},
    "Sound.railgun": {"displayName": "Railgun"},
    "Sound.rain": {"displayName": "Rain"},
    "Sound.release": {"displayName": "Release"},
    "Sound.respawn": {"displayName": "Respawn"},
    "Sound.respawning": {"displayName": "Respawning"},
    "Sound.rockBreak": {"displayName": "Rock Break"},
    "Sound.sap": {"displayName": "Sap"},
    "Sound.shield": {"displayName": "Shield"},
    "Sound.shockBlast": {"displayName": "Shock Blast"},
    "Sound.shoot": {"displayName": "Shoot"},
    "Sound.shootAlt": {"displayName": "Shoot Alt"},
    "Sound.shootAltLong": {"displayName": "Shoot Alt Long"},
    "Sound.shootBig": {"displayName": "Shoot Big"},
    "Sound.shootSmite": {"displayName": "Shoot Smite"},
    "Sound.shootSnap": {"displayName": "Shoot Snap"},
    "Sound.shotgun": {"displayName": "Shotgun"},
    "Sound.smelter": {"displayName": "Smelter"},
    "Sound.spark": {"displayName": "Spark"},
    "Sound.spellLoop": {"displayName": "Spell Loop"},
    "Sound.splash": {"displayName": "Splash"},
    "Sound.spray": {"displayName": "Spray"},
    "Sound.steam": {"displayName": "Steam"},
    "Sound.swish": {"displayName": "Swish"},
    "Sound.techloop": {"displayName": "Techloop"},
    "Sound.thruster": {"displayName": "Thruster"},
    "Sound.titanExplosion": {"displayName": "Titan Explosion"},
    "Sound.torch": {"displayName": "Torch"},
    "Sound.tractorbeam": {"displayName": "Tractorbeam"},
    "Sound.unlock": {"displayName": "Unlock"},
    "Sound.wave": {"displayName": "Wave"},
    "Sound.wind": {"displayName": "Wind"},
    "Sound.wind2": {"displayName": "Wind 2"},
    "Sound.wind3": {"displayName": "Wind 3"},
    "Sound.windhowl": {"displayName": "Windhowl"},
    "Sound.none": {"displayName": "None"}
}
SOUND_TYPES = {}
for i in SOUND_TYPES_NOLOAD:
    # SOUND_TYPES_NOLOAD[i]['plugin'] = "generic"
    SOUND_TYPES[i] = SOUND_TYPES_NOLOAD[i]

ALL_SERPULO_CONTENT_TREE = {
    "coreShard": {"displayName": "Core Shard"},
    "conveyor": {"displayName": "Conveyor"},
    "junction": {"displayName": "Junction"},
    "router": {"displayName": "Router"},
    "advancedLaunchPad": {"displayName": "Advanced Launch Pad"},
    "landingPad": {"displayName": "Landing Pad"},
    "interplanetaryAccelerator": {"displayName": "Interplanetary Accelerator"},
    "distributor": {"displayName": "Distributor"},
    "sorter": {"displayName": "Sorter"},
    "invertedSorter": {"displayName": "Inverted Sorter"},
    "overflowGate": {"displayName": "Overflow Gate"},
    "underflowGate": {"displayName": "Underflow Gate"},
    "container": {"displayName": "Container"},
    "unloader": {"displayName": "Unloader"},
    "vault": {"displayName": "Vault"},
    "itemBridge": {"displayName": "Item Bridge"},
    "titaniumConveyor": {"displayName": "Titanium Conveyor"},
    "phaseConveyor": {"displayName": "Phase Conveyor"},
    "massDriver": {"displayName": "Mass Driver"},
    "payloadConveyor": {"displayName": "Payload Conveyor"},
    "payloadRouter": {"displayName": "Payload Router"},
    "armoredConveyor": {"displayName": "Armored Conveyor"},
    "plastaniumConveyor": {"displayName": "Plastanium Conveyor"},
    "coreFoundation": {"displayName": "Core Foundation"},
    "coreNucleus": {"displayName": "Core Nucleus"},
    "mechanicalDrill": {"displayName": "Mechanical Drill"},
    "mechanicalPump": {"displayName": "Mechanical Pump"},
    "conduit": {"displayName": "Conduit"},
    "liquidJunction": {"displayName": "Liquid Junction"},
    "liquidRouter": {"displayName": "Liquid Router"},
    "liquidContainer": {"displayName": "Liquid Container"},
    "liquidTank": {"displayName": "Liquid Tank"},
    "bridgeConduit": {"displayName": "Bridge Conduit"},
    "pulseConduit": {"displayName": "Pulse Conduit"},
    "phaseConduit": {"displayName": "Phase Conduit"},
    "platedConduit": {"displayName": "Plated Conduit"},
    "rotaryPump": {"displayName": "Rotary Pump"},
    "impulsePump": {"displayName": "Impulse Pump"},
    "graphitePress": {"displayName": "Graphite Press"},
    "pneumaticDrill": {"displayName": "Pneumatic Drill"},
    "cultivator": {"displayName": "Cultivator"},
    "laserDrill": {"displayName": "Laser Drill"},
    "blastDrill": {"displayName": "Blast Drill"},
    "waterExtractor": {"displayName": "Water Extractor"},
    "oilExtractor": {"displayName": "Oil Extractor"},
    "pyratiteMixer": {"displayName": "Pyratite Mixer"},
    "blastMixer": {"displayName": "Blast Mixer"},
    "siliconSmelter": {"displayName": "Silicon Smelter"},
    "sporePress": {"displayName": "Spore Press"},
    "coalCentrifuge": {"displayName": "Coal Centrifuge"},
    "multiPress": {"displayName": "Multi-Press"},
    "siliconCrucible": {"displayName": "Silicon Crucible"},
    "plastaniumCompressor": {"displayName": "Plastanium Compressor"},
    "phaseWeaver": {"displayName": "Phase Weaver"},
    "kiln": {"displayName": "Kiln"},
    "pulverizer": {"displayName": "Pulverizer"},
    "incinerator": {"displayName": "Incinerator"},
    "melter": {"displayName": "Melter"},
    "surgeSmelter": {"displayName": "Surge Smelter"},
    "separator": {"displayName": "Separator"},
    "disassembler": {"displayName": "Disassembler"},
    "cryofluidMixer": {"displayName": "Cryofluid Mixer"},
    "microProcessor": {"displayName": "Micro Processor"},
    "switchBlock": {"displayName": "Switch"},
    "message": {"displayName": "Message"},
    "logicDisplay": {"displayName": "Logic Display"},
    "largeLogicDisplay": {"displayName": "Large Logic Display"},
    "logicDisplayTile": {"displayName": "Logic Display Tile"},
    "memoryCell": {"displayName": "Memory Cell"},
    "memoryBank": {"displayName": "Memory Bank"},
    "logicProcessor": {"displayName": "Logic Processor"},
    "hyperProcessor": {"displayName": "Hyper Processor"},
    "illuminator": {"displayName": "Illuminator"},
    "combustionGenerator": {"displayName": "Combustion Generator"},
    "powerNode": {"displayName": "Power Node"},
    "powerNodeLarge": {"displayName": "Large Power Node"},
    "diode": {"displayName": "Diode"},
    "surgeTower": {"displayName": "Surge Tower"},
    "battery": {"displayName": "Battery"},
    "batteryLarge": {"displayName": "Large Battery"},
    "mender": {"displayName": "Mender"},
    "mendProjector": {"displayName": "Mend Projector"},
    "forceProjector": {"displayName": "Force Projector"},
    "overdriveProjector": {"displayName": "Overdrive Projector"},
    "overdriveDome": {"displayName": "Overdrive Dome"},
    "repairPoint": {"displayName": "Repair Point"},
    "repairTurret": {"displayName": "Repair Turret"},
    "steamGenerator": {"displayName": "Steam Generator"},
    "thermalGenerator": {"displayName": "Thermal Generator"},
    "differentialGenerator": {"displayName": "Differential Generator"},
    "thoriumReactor": {"displayName": "Thorium Reactor"},
    "impactReactor": {"displayName": "Impact Reactor"},
    "rtgGenerator": {"displayName": "RTG Generator"},
    "solarPanel": {"displayName": "Solar Panel"},
    "largeSolarPanel": {"displayName": "Large Solar Panel"},
    "duo": {"displayName": "Duo"},
    "copperWall": {"displayName": "Copper Wall"},
    "copperWallLarge": {"displayName": "Large Copper Wall"},
    "scrapWall": {"displayName": "Scrap Wall"},
    "scrapWallLarge": {"displayName": "Large Scrap Wall"},
    "scrapWallHuge": {"displayName": "Huge Scrap Wall"},
    "scrapWallGigantic": {"displayName": "Gigantic Scrap Wall"},
    "titaniumWall": {"displayName": "Titanium Wall"},
    "titaniumWallLarge": {"displayName": "Large Titanium Wall"},
    "door": {"displayName": "Door"},
    "doorLarge": {"displayName": "Large Door"},
    "plastaniumWall": {"displayName": "Plastanium Wall"},
    "plastaniumWallLarge": {"displayName": "Large Plastanium Wall"},
    "thoriumWall": {"displayName": "Thorium Wall"},
    "thoriumWallLarge": {"displayName": "Large Thorium Wall"},
    "surgeWall": {"displayName": "Surge Wall"},
    "surgeWallLarge": {"displayName": "Large Surge Wall"},
    "phaseWall": {"displayName": "Phase Wall"},
    "phaseWallLarge": {"displayName": "Large Phase Wall"},
    "scatter": {"displayName": "Scatter"},
    "hail": {"displayName": "Hail"},
    "salvo": {"displayName": "Salvo"},
    "swarmer": {"displayName": "Swarmer"},
    "cyclone": {"displayName": "Cyclone"},
    "spectre": {"displayName": "Spectre"},
    "ripple": {"displayName": "Ripple"},
    "fuse": {"displayName": "Fuse"},
    "scorch": {"displayName": "Scorch"},
    "arc": {"displayName": "Arc"},
    "wave": {"displayName": "Wave"},
    "parallax": {"displayName": "Parallax"},
    "segment": {"displayName": "Segment"},
    "tsunami": {"displayName": "Tsunami"},
    "lancer": {"displayName": "Lancer"},
    "meltdown": {"displayName": "Meltdown"},
    "foreshadow": {"displayName": "Foreshadow"},
    "shockMine": {"displayName": "Shock Mine"},
    "groundFactory": {"displayName": "Ground Factory"},
    "dagger": {"displayName": "Dagger"},
    "mace": {"displayName": "Mace"},
    "fortress": {"displayName": "Fortress"},
    "scepter": {"displayName": "Scepter"},
    "reign": {"displayName": "Reign"},
    "nova": {"displayName": "Nova"},
    "pulsar": {"displayName": "Pulsar"},
    "quasar": {"displayName": "Quasar"},
    "vela": {"displayName": "Vela"},
    "corvus": {"displayName": "Corvus"},
    "crawler": {"displayName": "Crawler"},
    "atrax": {"displayName": "Atrax"},
    "spiroct": {"displayName": "Spiroct"},
    "arkyid": {"displayName": "Arkyid"},
    "toxopid": {"displayName": "Toxopid"},
    "airFactory": {"displayName": "Air Factory"},
    "flare": {"displayName": "Flare"},
    "horizon": {"displayName": "Horizon"},
    "zenith": {"displayName": "Zenith"},
    "antumbra": {"displayName": "Antumbra"},
    "eclipse": {"displayName": "Eclipse"},
    "mono": {"displayName": "Mono"},
    "poly": {"displayName": "Poly"},
    "mega": {"displayName": "Mega"},
    "quad": {"displayName": "Quad"},
    "oct": {"displayName": "Oct"},
    "navalFactory": {"displayName": "Naval Factory"},
    "risso": {"displayName": "Risso"},
    "minke": {"displayName": "Minke"},
    "bryde": {"displayName": "Bryde"},
    "sei": {"displayName": "Sei"},
    "omura": {"displayName": "Omura"},
    "retusa": {"displayName": "Retusa"},
    "oxynoe": {"displayName": "Oxynoe"},
    "cyerce": {"displayName": "Cyerce"},
    "aegires": {"displayName": "Aegires"},
    "navanax": {"displayName": "Navanax"},
    "additiveReconstructor": {"displayName": "Additive Reconstructor"},
    "multiplicativeReconstructor": {"displayName": "Multiplicative Reconstructor"},
    "exponentialReconstructor": {"displayName": "Exponential Reconstructor"},
    "tetrativeReconstructor": {"displayName": "Tetrative Reconstructor"},
    "groundZero": {"displayName": "Ground Zero"}
}

ALL_EREKIR_CONTENT_TREE = {
    "coreBastion": {"displayName": "Core: Bastion"},
    "coreCitadel": {"displayName": "Core: Citadel"},
    "coreAcropolis": {"displayName": "Core: Acropolis"},
    "largeLiquidTank": {"displayName": "Large Liquid Tank"},
    "plasmaBore": {"displayName": "Plasma Bore"},
    "beamDrill": {"displayName": "Beam Drill"},
    "electricHeater": {"displayName": "Electric Heater"},
    "plasmaPump": {"displayName": "Plasma Pump"},
    "cryofluidPump": {"displayName": "Cryofluid Pump"},
    "slagHeater": {"displayName": "Slag Heater"},
    "separator2": {"displayName": "Erekir Separator"},
    "smelter": {"displayName": "Smelter"},
    "electrolyzer": {"displayName": "Electrolyzer"},
    "atmosphericCondenser": {"displayName": "Atmospheric Condenser"},
    "oxidationChamber": {"displayName": "Oxidation Chamber"},
    "slagIncinerator": {"displayName": "Slag Incinerator"},
    "phaseHeater": {"displayName": "Phase Heater"},
    "heatRedirector": {"displayName": "Heat Redirector"},
    "heatRouter": {"displayName": "Heat Router"},
    "heatLink": {"displayName": "Heat Link"},
    "batteryDiode": {"displayName": "Battery Diode"},
    "longPowerNode": {"displayName": "Long Power Node"},
    "shockwaveTower": {"displayName": "Shockwave Tower"},
    "empTower": {"displayName": "EMP Tower"},
    "surgeTower2": {"displayName": "Surge Tower Mk2"},
    "deconstructor": {"displayName": "Deconstructor"},
    "constructor": {"displayName": "Constructor"},
    "constructorLarge": {"displayName": "Large Constructor"},
    "unitCargoLoader": {"displayName": "Unit Cargo Loader"},
    "payloadLoader": {"displayName": "Payload Loader"},
    "payloadUnloader": {"displayName": "Payload Unloader"},
    "payloadMassDriver": {"displayName": "Payload Mass Driver"},
    "airblastDrill": {"displayName": "Airblast Drill"},
    "siliconArcFurnace": {"displayName": "Silicon Arc Furnace"},
    "berylliumCompressor": {"displayName": "Beryllium Compressor"},
    "titaniumCrucible": {"displayName": "Titanium Crucible"},
    "blastSmelter": {"displayName": "Blast Smelter"},
    "electricMELT": {"displayName": "Electric MELT"},
    "coreNucleus": {"displayName": "Core: Nucleus"},
    "plasmaConveyor": {"displayName": "Plasma Conveyor"},
    "plasmaRouter": {"displayName": "Plasma Router"},
    "plasmaJunction": {"displayName": "Plasma Junction"},
    "burstDrill": {"displayName": "Burst Drill"},
    "disassembler2": {"displayName": "Disassembler Mk2"},
    "basicAssembler": {"displayName": "Basic Assembler"},
    "advancedAssembler": {"displayName": "Advanced Assembler"},
    "electromagneticAssembler": {"displayName": "Electromagnetic Assembler"},
    "constructor2": {"displayName": "Constructor Mk2"},
    "constructorLarge2": {"displayName": "Large Constructor Mk2"},
    "duct": {"displayName": "Duct"},
    "ductRouter": {"displayName": "Duct Router"},
    "ductBridge": {"displayName": "Duct Bridge"},
    "berylliumWall": {"displayName": "Beryllium Wall"},
    "berylliumWallLarge": {"displayName": "Large Beryllium Wall"},
    "tungstenWall": {"displayName": "Tungsten Wall"},
    "tungstenWallLarge": {"displayName": "Large Tungsten Wall"},
    "blastDoor": {"displayName": "Blast Door"},
    "blastDoorLarge": {"displayName": "Large Blast Door"},
    "reinforcedSurgeWall": {"displayName": "Reinforced Surge Wall"},
    "reinforcedSurgeWallLarge": {"displayName": "Large Reinforced Surge Wall"},
    "reinforcedPhaseWall": {"displayName": "Reinforced Phase Wall"},
    "reinforcedPhaseWallLarge": {"displayName": "Large Reinforced Phase Wall"},
    "shockwaveMine": {"displayName": "Shockwave Mine"},
    "tectonic": {"displayName": "Tectonic"},
    "quake": {"displayName": "Quake"},
    "smite": {"displayName": "Smite"},
    "diffuse": {"displayName": "Diffuse"},
    "locus": {"displayName": "Locus"},
    "oblivion": {"displayName": "Oblivion"},
    "manifold": {"displayName": "Manifold"},
    "artemis": {"displayName": "Artemis"},
    "novae": {"displayName": "Novae"},
    "eclipse2": {"displayName": "Eclipse Mk2"},
    "merui": {"displayName": "Merui"},
    "cleroi": {"displayName": "Cleroi"},
    "anthicus": {"displayName": "Anthicus"},
    "tecta": {"displayName": "Tecta"},
    "precept": {"displayName": "Precept"},
    "vanquish": {"displayName": "Vanquish"},
    "conquer": {"displayName": "Conquer"},
    "assembleGroundFactory": {"displayName": "Assemble Ground Factory"},
    "assembleAirFactory": {"displayName": "Assemble Air Factory"},
    "assembleNavalFactory": {"displayName": "Assemble Naval Factory"},
    "tankReconstructor": {"displayName": "Tank Reconstructor"},
    "shipReconstructor": {"displayName": "Ship Reconstructor"},
    "airReconstructor": {"displayName": "Air Reconstructor"},
    "mechReconstructor": {"displayName": "Mech Reconstructor"},
    "tankT3Reconstructor": {"displayName": "T3 Tank Reconstructor"},
    "shipT3Reconstructor": {"displayName": "T3 Ship Reconstructor"},
    "airT3Reconstructor": {"displayName": "T3 Air Reconstructor"},
    "mechT3Reconstructor": {"displayName": "T3 Mech Reconstructor"},
    "tankT4Reconstructor": {"displayName": "T4 Tank Reconstructor"},
    "shipT4Reconstructor": {"displayName": "T4 Ship Reconstructor"},
    "airT4Reconstructor": {"displayName": "T4 Air Reconstructor"},
    "mechT4Reconstructor": {"displayName": "T4 Mech Reconstructor"},
    "planetaryTerminal": {"displayName": "Planetary Terminal"},
    "commandCenter": {"displayName": "Command Center"}
}


CACHE_LAYER = {
    "CacheLayer.water": {"displayName": "Water", "plugin": "generic"},
    "CacheLayer.mud": {"displayName": "Mud", "plugin": "generic"},
    "CacheLayer.cryofluid": {"displayName": "Cryofluid", "plugin": "generic"},
    "CacheLayer.tar": {"displayName": "Tar", "plugin": "generic"},
    "CacheLayer.slag": {"displayName": "Slag", "plugin": "generic"},
    "CacheLayer.arkycite": {"displayName": "Arkycite", "plugin": "generic"},
    "CacheLayer.space": {"displayName": "Space", "plugin": "generic"},
    "CacheLayer.normal": {"displayName": "Normal", "plugin": "generic"},
    "CacheLayer.walls": {"displayName": "Walls", "plugin": "generic"},
}

EFFECTS_TYPE_NOLOAD = {
    "Effect.none": {"displayName": "None"},
    "Effect.blockCrash": {"displayName": "Block Crash"},
    "Effect.trailFade": {"displayName": "Trail Fade"},
    "Effect.unitSpawn": {"displayName": "Unit Spawn"},
    "Effect.unitCapKill": {"displayName": "Unit Cap Kill"},
    "Effect.unitEnvKill": {"displayName": "Unit Env Kill"},
    "Effect.unitControl": {"displayName": "Unit Control"},
    "Effect.unitDespawn": {"displayName": "Unit Despawn"},
    "Effect.unitSpirit": {"displayName": "Unit Spirit"},
    "Effect.itemTransfer": {"displayName": "Item Transfer"},
    "Effect.pointBeam": {"displayName": "Point Beam"},
    "Effect.pointHit": {"displayName": "Point Hit"},
    "Effect.lightning": {"displayName": "Lightning"},
    "Effect.coreBuildShockwave": {"displayName": "Core Build Shockwave"},
    "Effect.coreBuildBlock": {"displayName": "Core Build Block"},
    "Effect.pointShockwave": {"displayName": "Point Shockwave"},
    "Effect.moveCommand": {"displayName": "Move Command"},
    "Effect.attackCommand": {"displayName": "Attack Command"},
    "Effect.commandSend": {"displayName": "Command Send"},
    "Effect.upgradeCore": {"displayName": "Upgrade Core"},
    "Effect.upgradeCoreBloom": {"displayName": "Upgrade Core Bloom"},
    "Effect.placeBlock": {"displayName": "Place Block"},
    "Effect.coreLaunchConstruct": {"displayName": "Core Launch Construct"},
    "Effect.tapBlock": {"displayName": "Tap Block"},
    "Effect.breakBlock": {"displayName": "Break Block"},
    "Effect.payloadDeposit": {"displayName": "Payload Deposit"},
    "Effect.select": {"displayName": "Select"},
    "Effect.smoke": {"displayName": "Smoke"},
    "Effect.fallSmoke": {"displayName": "Fall Smoke"},
    "Effect.unitWreck": {"displayName": "Unit Wreck"},
    "Effect.rocketSmoke": {"displayName": "Rocket Smoke"},
    "Effect.rocketSmokeLarge": {"displayName": "Rocket Smoke Large"},
    "Effect.magmasmoke": {"displayName": "Magma Smoke"},
    "Effect.spawn": {"displayName": "Spawn"},
    "Effect.unitAssemble": {"displayName": "Unit Assemble"},
    "Effect.padlaunch": {"displayName": "Pad Launch"},
    "Effect.breakProp": {"displayName": "Break Prop"},
    "Effect.unitDrop": {"displayName": "Unit Drop"},
    "Effect.unitLand": {"displayName": "Unit Land"},
    "Effect.unitDust": {"displayName": "Unit Dust"},
    "Effect.unitLandSmall": {"displayName": "Unit Land Small"},
    "Effect.unitPickup": {"displayName": "Unit Pickup"},
    "Effect.crawlDust": {"displayName": "Crawl Dust"},
    "Effect.landShock": {"displayName": "Land Shock"},
    "Effect.pickup": {"displayName": "Pickup"},
    "Effect.sparkExplosion": {"displayName": "Spark Explosion"},
    "Effect.titanExplosion": {"displayName": "Titan Explosion"},
    "Effect.titanSmoke": {"displayName": "Titan Smoke"},
    "Effect.missileTrailSmoke": {"displayName": "Missile Trail Smoke"},
    "Effect.neoplasmSplat": {"displayName": "Neoplasm Splat"},
    "Effect.scatheExplosion": {"displayName": "Scathe Explosion"},
    "Effect.scatheLight": {"displayName": "Scathe Light"},
    "Effect.scatheSlash": {"displayName": "Scathe Slash"},
    "Effect.dynamicSpikes": {"displayName": "Dynamic Spikes"},
    "Effect.greenBomb": {"displayName": "Green Bomb"},
    "Effect.greenLaserCharge": {"displayName": "Green Laser Charge"},
    "Effect.greenLaserChargeSmall": {"displayName": "Green Laser Charge Small"},
    "Effect.greenCloud": {"displayName": "Green Cloud"},
    "Effect.healWaveDynamic": {"displayName": "Heal Wave Dynamic"},
    "Effect.healWave": {"displayName": "Heal Wave"},
    "Effect.heal": {"displayName": "Heal"},
    "Effect.dynamicWave": {"displayName": "Dynamic Wave"},
    "Effect.shieldWave": {"displayName": "Shield Wave"},
    "Effect.shieldApply": {"displayName": "Shield Apply"},
    "Effect.disperseTrail": {"displayName": "Disperse Trail"},
    "Effect.hitBulletSmall": {"displayName": "Hit Bullet Small"},
    "Effect.hitBulletColor": {"displayName": "Hit Bullet Color"},
    "Effect.hitSquaresColor": {"displayName": "Hit Squares Color"},
    "Effect.hitFuse": {"displayName": "Hit Fuse"},
    "Effect.hitBulletBig": {"displayName": "Hit Bullet Big"},
    "Effect.hitFlameSmall": {"displayName": "Hit Flame Small"},
    "Effect.hitFlamePlasma": {"displayName": "Hit Flame Plasma"},
    "Effect.hitLiquid": {"displayName": "Hit Liquid"},
    "Effect.hitLaserBlast": {"displayName": "Hit Laser Blast"},
    "Effect.hitEmpSpark": {"displayName": "Hit EMP Spark"},
    "Effect.hitLancer": {"displayName": "Hit Lancer"},
    "Effect.hitBeam": {"displayName": "Hit Beam"},
    "Effect.hitFlameBeam": {"displayName": "Hit Flame Beam"},
    "Effect.hitMeltdown": {"displayName": "Hit Meltdown"},
    "Effect.hitMeltHeal": {"displayName": "Hit Melt Heal"},
    "Effect.instBomb": {"displayName": "Inst Bomb"},
    "Effect.instTrail": {"displayName": "Inst Trail"},
    "Effect.instShoot": {"displayName": "Inst Shoot"},
    "Effect.instHit": {"displayName": "Inst Hit"},
    "Effect.hitLaser": {"displayName": "Hit Laser"},
    "Effect.hitLaserColor": {"displayName": "Hit Laser Color"},
    "Effect.despawn": {"displayName": "Despawn"},
    "Effect.airBubble": {"displayName": "Air Bubble"},
    "Effect.flakExplosion": {"displayName": "Flak Explosion"},
    "Effect.plasticExplosion": {"displayName": "Plastic Explosion"},
    "Effect.plasticExplosionFlak": {"displayName": "Plastic Explosion Flak"},
    "Effect.blastExplosion": {"displayName": "Blast Explosion"},
    "Effect.sapExplosion": {"displayName": "Sap Explosion"},
    "Effect.massiveExplosion": {"displayName": "Massive Explosion"},
    "Effect.artilleryTrail": {"displayName": "Artillery Trail"},
    "Effect.incendTrail": {"displayName": "Incendiary Trail"},
    "Effect.missileTrail": {"displayName": "Missile Trail"},
    "Effect.missileTrailShort": {"displayName": "Missile Trail Short"},
    "Effect.colorTrail": {"displayName": "Color Trail"},
    "Effect.absorb": {"displayName": "Absorb"},
    "Effect.forceShrink": {"displayName": "Force Shrink"},
    "Effect.flakExplosionBig": {"displayName": "Flak Explosion Big"},
    "Effect.burning": {"displayName": "Burning"},
    "Effect.fireRemove": {"displayName": "Fire Remove"},
    "Effect.fire": {"displayName": "Fire"},
    "Effect.fireHit": {"displayName": "Fire Hit"},
    "Effect.fireSmoke": {"displayName": "Fire Smoke"},
    "Effect.neoplasmHeal": {"displayName": "Neoplasm Heal"},
    "Effect.steam": {"displayName": "Steam"},
    "Effect.ventSteam": {"displayName": "Vent Steam"},
    "Effect.drillSteam": {"displayName": "Drill Steam"},
    "Effect.fluxVapor": {"displayName": "Flux Vapor"},
    "Effect.vapor": {"displayName": "Vapor"},
    "Effect.vaporSmall": {"displayName": "Vapor Small"},
    "Effect.fireballsmoke": {"displayName": "Fireball Smoke"},
    "Effect.ballfire": {"displayName": "Ball Fire"},
    "Effect.freezing": {"displayName": "Freezing"},
    "Effect.melting": {"displayName": "Melting"},
    "Effect.wet": {"displayName": "Wet"},
    "Effect.muddy": {"displayName": "Muddy"},
    "Effect.sapped": {"displayName": "Sapped"},
    "Effect.electrified": {"displayName": "Electrified"},
    "Effect.sporeSlowed": {"displayName": "Spore Slowed"},
    "Effect.oily": {"displayName": "Oily"},
    "Effect.overdriven": {"displayName": "Overdriven"},
    "Effect.overclocked": {"displayName": "Overclocked"},
    "Effect.dropItem": {"displayName": "Drop Item"},
    "Effect.shockwave": {"displayName": "Shockwave"},
    "Effect.bigShockwave": {"displayName": "Big Shockwave"},
    "Effect.spawnShockwave": {"displayName": "Spawn Shockwave"},
    "Effect.explosion": {"displayName": "Explosion"},
    "Effect.dynamicExplosion": {"displayName": "Dynamic Explosion"},
    "Effect.reactorExplosion": {"displayName": "Reactor Explosion"},
    "Effect.impactReactorExplosion": {"displayName": "Impact Reactor Explosion"},
    "Effect.blockExplosionSmoke": {"displayName": "Block Explosion Smoke"},
    "Effect.smokePuff": {"displayName": "Smoke Puff"},
    "Effect.shootSmall": {"displayName": "Shoot Small"},
    "Effect.shootSmallColor": {"displayName": "Shoot Small Color"},
    "Effect.shootHeal": {"displayName": "Shoot Heal"},
    "Effect.shootHealYellow": {"displayName": "Shoot Heal Yellow"},
    "Effect.shootSmallSmoke": {"displayName": "Shoot Small Smoke"},
    "Effect.shootBig": {"displayName": "Shoot Big"},
    "Effect.shootBig2": {"displayName": "Shoot Big 2"},
    "Effect.shootBigColor": {"displayName": "Shoot Big Color"},
    "Effect.shootTitan": {"displayName": "Shoot Titan"},
    "Effect.shootBigSmoke": {"displayName": "Shoot Big Smoke"},
    "Effect.shootBigSmoke2": {"displayName": "Shoot Big Smoke 2"},
    "Effect.shootSmokeDisperse": {"displayName": "Shoot Smoke Disperse"},
    "Effect.shootSmokeSquare": {"displayName": "Shoot Smoke Square"},
    "Effect.shootSmokeSquareSparse": {"displayName": "Shoot Smoke Square Sparse"},
    "Effect.shootSmokeSquareBig": {"displayName": "Shoot Smoke Square Big"},
    "Effect.shootSmokeTitan": {"displayName": "Shoot Smoke Titan"},
    "Effect.shootSmokeSmite": {"displayName": "Shoot Smoke Smite"},
    "Effect.shootSmokeMissile": {"displayName": "Shoot Smoke Missile"},
    "Effect.regenParticle": {"displayName": "Regen Particle"},
    "Effect.regenSuppressParticle": {"displayName": "Regen Suppress Particle"},
    "Effect.regenSuppressSeek": {"displayName": "Regen Suppress Seek"},
    "Effect.surgeCruciSmoke": {"displayName": "Surge Crucible Smoke"},
    "Effect.neoplasiaSmoke": {"displayName": "Neoplasia Smoke"},
    "Effect.heatReactorSmoke": {"displayName": "Heat Reactor Smoke"},
    "Effect.circleColorSpark": {"displayName": "Circle Color Spark"},
    "Effect.colorSpark": {"displayName": "Color Spark"},
    "Effect.colorSparkBig": {"displayName": "Color Spark Big"},
    "Effect.randLifeSpark": {"displayName": "Random Life Spark"},
    "Effect.shootPayloadDriver": {"displayName": "Shoot Payload Driver"},
    "Effect.shootSmallFlame": {"displayName": "Shoot Small Flame"},
    "Effect.shootPyraFlame": {"displayName": "Shoot Pyra Flame"},
    "Effect.shootLiquid": {"displayName": "Shoot Liquid"},
    "Effect.casing1": {"displayName": "Casing 1"},
    "Effect.casing2": {"displayName": "Casing 2"},
    "Effect.casing3": {"displayName": "Casing 3"},
    "Effect.casing4": {"displayName": "Casing 4"},
    "Effect.casing2Double": {"displayName": "Casing 2 Double"},
    "Effect.casing3Double": {"displayName": "Casing 3 Double"},
    "Effect.railShoot": {"displayName": "Rail Shoot"},
    "Effect.railTrail": {"displayName": "Rail Trail"},
    "Effect.railHit": {"displayName": "Rail Hit"},
    "Effect.lancerLaserShoot": {"displayName": "Lancer Laser Shoot"},
    "Effect.lancerLaserShootSmoke": {"displayName": "Lancer Laser Shoot Smoke"},
    "Effect.lancerLaserCharge": {"displayName": "Lancer Laser Charge"},
    "Effect.lancerLaserChargeBegin": {"displayName": "Lancer Laser Charge Begin"},
    "Effect.lightningCharge": {"displayName": "Lightning Charge"},
    "Effect.sparkShoot": {"displayName": "Spark Shoot"},
    "Effect.lightningShoot": {"displayName": "Lightning Shoot"},
    "Effect.thoriumShoot": {"displayName": "Thorium Shoot"},
    "Effect.reactorsmoke": {"displayName": "Reactor Smoke"},
    "Effect.redgeneratespark": {"displayName": "Red Generate Spark"},
    "Effect.turbinegenerate": {"displayName": "Turbine Generate"},
    "Effect.generatespark": {"displayName": "Generate Spark"},
    "Effect.fuelburn": {"displayName": "Fuel Burn"},
    "Effect.incinerateSlag": {"displayName": "Incinerate Slag"},
    "Effect.coreBurn": {"displayName": "Core Burn"},
    "Effect.plasticburn": {"displayName": "Plastic Burn"},
    "Effect.conveyorPoof": {"displayName": "Conveyor Poof"},
    "Effect.pulverize": {"displayName": "Pulverize"},
    "Effect.pulverizeRed": {"displayName": "Pulverize Red"},
    "Effect.pulverizeSmall": {"displayName": "Pulverize Small"},
    "Effect.pulverizeMedium": {"displayName": "Pulverize Medium"},
    "Effect.producesmoke": {"displayName": "Produce Smoke"},
    "Effect.artilleryTrailSmoke": {"displayName": "Artillery Trail Smoke"},
    "Effect.smokeCloud": {"displayName": "Smoke Cloud"},
    "Effect.smeltsmoke": {"displayName": "Smelt Smoke"},
    "Effect.coalSmeltsmoke": {"displayName": "Coal Smelt Smoke"},
    "Effect.formsmoke": {"displayName": "Form Smoke"},
    "Effect.blastsmoke": {"displayName": "Blast Smoke"},
    "Effect.lava": {"displayName": "Lava"},
    "Effect.dooropen": {"displayName": "Door Open"},
    "Effect.doorclose": {"displayName": "Door Close"},
    "Effect.dooropenlarge": {"displayName": "Door Open Large"},
    "Effect.doorcloselarge": {"displayName": "Door Close Large"},
    "Effect.generate": {"displayName": "Generate"},
    "Effect.mineWallSmall": {"displayName": "Mine Wall Small"},
    "Effect.mineSmall": {"displayName": "Mine Small"},
    "Effect.mine": {"displayName": "Mine"},
    "Effect.mineBig": {"displayName": "Mine Big"},
    "Effect.mineHuge": {"displayName": "Mine Huge"},
    "Effect.mineImpact": {"displayName": "Mine Impact"},
    "Effect.mineImpactWave": {"displayName": "Mine Impact Wave"},
    "Effect.payloadReceive": {"displayName": "Payload Receive"},
    "Effect.teleportActivate": {"displayName": "Teleport Activate"},
    "Effect.teleport": {"displayName": "Teleport"},
    "Effect.teleportOut": {"displayName": "Teleport Out"},
    "Effect.ripple": {"displayName": "Ripple"},
    "Effect.bubble": {"displayName": "Bubble"},
    "Effect.launch": {"displayName": "Launch"},
    "Effect.launchPod": {"displayName": "Launch Pod"},
    "Effect.healWaveMend": {"displayName": "Heal Wave Mend"},
    "Effect.overdriveWave": {"displayName": "Overdrive Wave"},
    "Effect.healBlock": {"displayName": "Heal Block"},
    "Effect.healBlockFull": {"displayName": "Heal Block Full"},
    "Effect.rotateBlock": {"displayName": "Rotate Block"},
    "Effect.lightBlock": {"displayName": "Light Block"},
    "Effect.overdriveBlockFull": {"displayName": "Overdrive Block Full"},
    "Effect.shieldBreak": {"displayName": "Shield Break"},
    "Effect.coreLandDust": {"displayName": "Core Land Dust"},
    "Effect.unitShieldBreak": {"displayName": "Unit Shield Break"},
    "Effect.chainLightning": {"displayName": "Chain Lightning"},
    "Effect.chainEmp": {"displayName": "Chain EMP"},
    "Effect.legDestroy": {"displayName": "Leg Destroy"}
}
EFFECTS_TYPE = {}
for i in EFFECTS_TYPE_NOLOAD:
    # EFFECTS_TYPE_NOLOAD[i]['plugin'] = "generic"
    EFFECTS_TYPE[i] = EFFECTS_TYPE_NOLOAD[i]

CONTENT_FOLDER = "~/src/{package}/content"


