# Generated from: UI\Content\BoolSelect.py
from typing import Any, Optional, Union, Type, ClassVar
from collections.abc import Callable, Coroutine

class Widget(QCheckBox, BaseCustomWidget):
    def __init__(self: Any) -> None: ...
    def set_value(self: Any, value: str | bool) -> None: ...
    def value(self: Any) -> bool: ...