# Generated from: UI\Content\CacheLayer.py
from typing import Any, Optional, Union, Type, ClassVar
from collections.abc import Callable, Coroutine

class Widget(SearchBox, BaseCustomWidget):
    def __init__(self: Any) -> None: ...
    def set_value(self: Any, value: Any) -> None: ...
    def value(self: Any) -> str: ...