# Generated from: UI\Window\Launcher.py
from typing import Any, Optional, Union, Type, ClassVar
from collections.abc import Callable, Coroutine

class ProjectActionMenu(QMenu):
    def __init__(self: Any, project_name: Any, parent: Any) -> None: ...
    def emit_action(self: Any, action_id: Any) -> None: ...
class ProjectItemWidget(QWidget):
    def __init__(self: Any, name: Any, icon: Any, data: Any, parent: Any) -> None: ...
    def set_icon(self: Any, icon: Any) -> None: ...
    def handle_menu_action(self: Any, action_id: Any) -> None: ...
class LauncherWindow(QMainWindow):
    def __init__(self: Any) -> None: ...
    def setup_ui(self: Any) -> None: ...
    def setup_toolbar_buttons(self: Any, toolbar: Any) -> None: ...
    def add_project(self: Any, name: Any, icon: Any, data: Any) -> None: ...
    def show_context_menu(self: Any, pos: Any) -> None: ...
    def handle_project_action(self: Any, data: Any, action_id: Any) -> None: ...
    def handle_double_click(self: Any, item: Any) -> None: ...
    def handle_delete_project(self: Any, data: Any) -> None: ...
    def remove_project(self: Any, data: Any) -> None: ...
    def closeEvent(self: Any, event: Any) -> None: ...